### ISSUE TITLE
how to compile pdf from command line?

### ISSUE THREAD

**Issue by fucusy** [CheckBoxStudio/BUAAThesis#1]
how to compile pdf from command line?
I compile pdf using command `pdflatex Template.tex` from macOS 10.12.6, and get the error result like this.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Critical ctex error: "fontset-unavailable"
!
! CTeX fontset `mac' is unavailable in current mode.
!
! See the ctex documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.47   }
```

**Comment by weiquanmao** [comment]
Use the latest repo (buaa v1.1, along with buaa_mac v1.0a), where a class template for Mac system is added. Do remember to change class `buaa` to `buaa_mac` (in file *Template.tex*) and compile with **XeLaTeX**.
```
xelatex Template.tex
```
