### ISSUE TITLE
行距与子图标题有问题

### ISSUE THREAD

**Issue by huangteng1220** [CheckBoxStudio/BUAAThesis#14]
本人使用Mac版本，发现以下问题：

1、利用该模版生成的PDF正文行距不知道是多少，感觉有点大，明显与Word版本的正文行距不一样。标准的行距应该是1.5倍。可以通过Word满一页的文字测试来测试，该模版却需要两页。

2、当一个图里面含有两个子图的时候，两个子图的标题没有加粗。

不知道使用该模版的大牛，是否遇到类似的问题？
请求帮助，谢谢！！！！

**Comment by nypdmax** [comment]
没有发现这个问题，我和readme的环境类似。特意去论文里找了一页半满字的对比了下，貌似texstudio出来的比word还少几行。

**Comment by nypdmax** [comment]
caption加粗问题，\textbf可解
