### ISSUE TITLE
Tex模板中不包含书脊？

### ISSUE THREAD

**Issue by nypdmax** [CheckBoxStudio/BUAAThesis#15]
刚刚对照研究生手册和生成的pdf，发现少了论文书脊这一项。检查后发现模板是不包含这个的，请问大家都是怎么解决这个问题的？

**Comment by weiquanmao** [comment]
书脊可以另做
ps 应该不用管这个吧，打印店都会帮弄好，甚者连封面页都是用打印店自己的

From Quanmao Wei.

在 2019年4月12日，10:45，Max <notifications@github.com<mailto:notifications@github.com>> 写道：


刚刚对照研究生手册和生成的pdf，发现少了论文书脊这一项。检查后发现模板是不包含这个的，请问大家都是怎么解决这个问题的？

**Comment by nypdmax** [comment]
Great！Noted with thx！
