### ISSUE TITLE
图表清单会按照章进行留白

### ISSUE THREAD

**Issue by zhangleiray007** [CheckBoxStudio/BUAAThesis#16]
您好，非常感谢提供LaTeX模板，整体感觉非常好用，不过最近遇到了一个问题就是图表清单中会不自然的有的行间距会比较大，后来发现这个间距大的地方正好的不同章的分界，想请教您怎么把这个不自然的间距去掉呢？期待您的回复。

**Comment by weiquanmao** [comment]
您好。
我这边试了一下（win+pdfLatex环境），没发现你说的问题，章内图表清单列表间距和章间基本是一致的。
方便给看一下你的排版结果吗？

**Comment by zhangleiray007** [comment]
您好。
非常感谢您的回复。我的环境是win10（vscode+texlive2019）。我的排版结果截图是这样的。



2019-10-10 

zhangleiray007 



发件人：WeiQM <notifications@github.com>
发送时间：2019-10-10 22:04
主题：Re: [CheckBoxStudio/BUAAThesis] 图表清单会按照章进行留白 (#16)
收件人："CheckBoxStudio/BUAAThesis"<BUAAThesis@noreply.github.com>
抄送："Lei Zhang"<zhangleiray007@163.com>,"Author"<author@noreply.github.com>

您好。
我这边试了一下（win+pdfLatex环境），没发现你说的问题，章内图表清单列表间距和章间基本是一致的。
方便给看一下你的排版结果吗？

**Comment by zhangleiray007** [comment]
您好，我的环境是win10(vscode+texlive2019)。排版结果如下：
![Clip(10-10-22-55-59)](https://user-images.githubusercontent.com/6381825/66582090-c8ad8880-ebb3-11e9-8a4c-9e4da6a8735a.png)

**Comment by weiquanmao** [comment]
你好，这边没收到你说的文件。

From Quanmao Wei.

在 2019年10月10日，23:16，Lei Zhang <notifications@github.com> 写道：

﻿

您好，我的环境是win10(vscode+texlive2019)。排版结果如下：
[Clip(10-10-22-55-59)]<https://user-images.githubusercontent.com/6381825/66582090-c8ad8880-ebb3-11e9-8a4c-9e4da6a8735a.png>

**Comment by hahakid** [comment]
我也发现了相同问题，但是listoffigures没有相关的代码说明。
确实 图/表 在使用自动生成的图清单/表清单时，章节之间的图行间距会扩大。应该是
\pdfbookmark[0]{图目录}{listoffigures}
      \listoffigures
      \clearpage
部分的问题。
![微信图片_20191021104255](https://user-images.githubusercontent.com/8140299/67172929-cfc46a00-f3ef-11e9-801b-60d3b76483ec.png)
![微信图片_20191021104248](https://user-images.githubusercontent.com/8140299/67172933-d18e2d80-f3ef-11e9-8363-35d1986c5c68.png)

**Comment by zhangleiray007** [comment]
嗯嗯，我也定位到这部分了，不过没有找到什么解决办法。

2019-10-21 

zhangleiray007 



发件人：superkid <notifications@github.com>
发送时间：2019-10-21 10:45
主题：Re: [CheckBoxStudio/BUAAThesis] 图表清单会按照章进行留白 (#16)
收件人："CheckBoxStudio/BUAAThesis"<BUAAThesis@noreply.github.com>
抄送："Lei Zhang"<zhangleiray007@163.com>,"Author"<author@noreply.github.com>

我也发现了相同问题，但是listoffigures没有相关的代码说明。
确实 图/表 在使用自动生成的图清单/表清单时，章节之间的图行间距会扩大。应该是
\pdfbookmark[0]{图目录}{listoffigures}
\listoffigures
\clearpage
部分的问题。

**Comment by hahakid** [comment]
@zhangleiray007 @weiquanmao 
I read the macros doc of **titletoc**, and find the following soluation:

{\pdfbookmark[0]{目录}{makecontextlist}

  \tableofcontents
  **\renewcommand\addvspace[1]{}**  % added
  \ifthenelse{\isundefined{\@listfigtab}}{}{%
    \ifthenelse{\equal{\@listfigtab}{on}}{%
      \clearpage
      \pdfbookmark[0]{图目录}{listoffigures}
      \listoffigures
      \clearpage
      \pdfbookmark[0]{表目录}{listoftables}
      \listoftables
    }{}
  }

It works fine on my paper, pls try.

**Comment by zhangleiray007** [comment]
@hahakid Thank you~~ It works on my paper, too.
