### ISSUE TITLE
每页的内容都不对齐

### ISSUE THREAD

**Issue by yezhiwen** [CheckBoxStudio/BUAAThesis#18]
![image](https://user-images.githubusercontent.com/15649165/67849096-e16ce680-fb40-11e9-8533-c611e460cbcf.png)

**Comment by weiquanmao** [comment]
这应该是你使用了双面打印设置`twoside`，左右页页边距设置不同。你可以：
1. 采用单面打印设置`oneside`；
2. 或自行修改cls文件中的页边距配置（300行左右位置）。
