### ISSUE TITLE
再报一个cls问题

### ISSUE THREAD

**Issue by hahakid** [CheckBoxStudio/BUAAThesis#19]
1. 结论部分章节需要和附录一样重新编号；
2. 部分段间距不等

**Comment by weiquanmao** [comment]
[084b573](https://github.com/CheckBoxStudio/BUAAThesis/commit/084b5730fcdffeb6030f0bbeb10f47a1f251952f) - 修复编号问题
> 无编号章节下子章节常用字母编号，不确定是否规范！

段间距不等不知道是不是因为弹性间距导致？

**Comment by hahakid** [comment]
@weiquanmao 我自己用的罗马，不过都差不多吧。 
弹性间距是什么控制的？现在大概就这么个问题了。有时候图/表会单独占一页。要是能够像word一样段内分开就好了。

**Comment by hahakid** [comment]
denotioan --> denotation
