### ISSUE TITLE
citation works in a wrong way if you compile it by xelatex on macOS

### ISSUE THREAD

**Issue by fucusy** [CheckBoxStudio/BUAAThesis#2]
citation works in a wrong way if you compile by xelatex when you add or remove some bib in ref.bib.

However, I already found solutions. What you need to do is run the four commands below,  suppose your tex filename is Template.tex

```
xelatex Template.tex
bibtex Template
xelatex Template.tex
xelatex Template.tex
```

see more from this [StackOverflow thread](https://tex.stackexchange.com/questions/119459/undefined-citations)
  
So, I thought some of you may update the readme?

**Comment by weiquanmao** [comment]
This is a typical toolchain for compiling with TeX and BibTeX, similar to ` pdflatex>bibtex>pdflatex>pdflatex` for pdfLaTeX. 

Anyway, thanks for your report!
