### ISSUE TITLE
参考文献显示出版地不详

### ISSUE THREAD

**Issue by maifulmax** [CheckBoxStudio/BUAAThesis#22]
英文参考文献很多都显示 [S.l.]或者[S.l.: s.n.]，中文文献也有相应问题。

以中文文献为例，bib文件写入中文文献：
@phdthesis{zhangzhiqiang2013,
  title={众包质量控制策略及评估算法研究},
  author={张志强 and 逄居升 and 谢晓芹 and 周永},
  journal={计算机学报},
  volume={36},
  number={8},
  pages={1636-1649},
  year={2013},
}
其显示的参考文献格式为：
张志强, 逄居升, 谢晓芹, 等. 众包质量控制策略及评估算法研究: 第36卷[D]. [出版地不详: 出版者不详], 2013: 1636–1649

**Comment by weiquanmao** [comment]
国标要求相关文献需要有出版地和/或出版者，如果没有会默认填 [出版地不详: 出版者不详]/[S.l.: s.n.]之类的。

如果你确实不想或无法添加出版地或出版者信息，你可以修改.bst文件：
```
...
FUNCTION {format.sine.nomine}
{ is.in.chinese
    { "[出版地不详]" }
    { "[s.n.]" }
  if$
}
...
FUNCTION {format.sine.loco.sine.nomine}
{ is.in.chinese
    { "[出版地不详: 出版者不详]" }
    { "[S.l.: s.n.]" }
  if$
}
...
```
将默认填写的内容删除，改为
```
...
FUNCTION {format.sine.nomine}
{ is.in.chinese
    { "" }
    { "" }
  if$
}
...
FUNCTION {format.sine.loco.sine.nomine}
{ is.in.chinese
    { "" }
    { "" }
  if$
}
```

> 修改时请确认你用的是`GBT7714-2015.bst`还是`GBT7714-2005.bst`。
> 未测试，应该能其作用。

**Comment by maifulmax** [comment]
> 国标要求相关文献需要有出版地和/或出版者，如果没有会默认填 [出版地不详: 出版者不详]/[S.l.: s.n.]之类的。
> 
> 如果你确实不想或无法添加出版地或出版者信息，你可以修改.bst文件：
> 
> ```
> ...
> FUNCTION {format.sine.nomine}
> { is.in.chinese
>     { "[出版地不详]" }
>     { "[s.n.]" }
>   if$
> }
> ...
> FUNCTION {format.sine.loco.sine.nomine}
> { is.in.chinese
>     { "[出版地不详: 出版者不详]" }
>     { "[S.l.: s.n.]" }
>   if$
> }
> ...
> ```
> 
> 将默认填写的内容删除，改为
> 
> ```
> ...
> FUNCTION {format.sine.nomine}
> { is.in.chinese
>     { "" }
>     { "" }
>   if$
> }
> ...
> FUNCTION {format.sine.loco.sine.nomine}
> { is.in.chinese
>     { "" }
>     { "" }
>   if$
> }
> ```
> 
> > 修改时请确认你用的是`GBT7714-2015.bst`还是`GBT7714-2005.bst`。
> > 未测试，应该能其作用。

举得例子中，只要把@phdthesis改为@article就行，而按照你这种删改方法，在英文文献中会多一些错误的冒号，例如：
 Fellbaum C. Wordnet: an electronic lexical database[M]. : MIT Press, 1998.

还有一个问题，中文中的作者列表最后接“等”字前会有个逗号，这个怎么去掉？这个属于bug把。

**Comment by weiquanmao** [comment]
‘等’前加逗号是正规格式哈
