### ISSUE TITLE
macos 编译后格式不正确

### ISSUE THREAD

**Issue by zhl2008** [CheckBoxStudio/BUAAThesis#24]
macos编译后出现以下问题：

1. 章节大标题与顶部的间距过大
2. 表格的表头和title没有加粗

<img width="519" alt="屏幕快照 2019-11-29 下午3 27 16" src="https://user-images.githubusercontent.com/11239020/69851525-db436480-12bc-11ea-9afe-08be57553702.png">
<img width="640" alt="屏幕快照 2019-11-29 下午3 26 28" src="https://user-images.githubusercontent.com/11239020/69851526-dbdbfb00-12bc-11ea-95c2-dc22b774446f.png">

使用的环境是mac Mojave 以及 xelatex (XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018))

**Comment by weiquanmao** [comment]
你可以试试最新更新[7139378](https://github.com/CheckBoxStudio/BUAAThesis/commit/71393786ccd1566634b36f3b97a4d38d3fe1d969)，把`buaa_mac.cls`里章节标题的`ctexset`的`fixskip`和`afterskip`打开了。Win下的XeLaTeX能正常编译，Mac下没测试过。如果没问题的话，应该能解决行间距问题。

P.S. 如果你方面的话，希望你帮我测一下Mac+XeLaTeX下`buaa.cls`能不能用，如果可以的话就不用`buaa_mac.cls`了。 

最后，关于加粗问题，目前还不清楚，抱歉。

**Comment by weiquanmao** [comment]
如果编译`buaa.cls`报`newtxmath.sty`里的`\lvert`错，先直接注释掉，谢谢~

**Comment by tpga001** [comment]
在Win10最新版以及TeXworks + XeLatex下编译也会出现无法加粗的问题，测试在captionsetup中使用labelfont和DeclareCaptionFormat中使用bfseries均无效。
