### ISSUE TITLE
论文题目太长

### ISSUE THREAD

**Issue by LaiPiXiong** [CheckBoxStudio/BUAAThesis#26]
论文题目太长以至于老师的职称不能出现在排版面内；若对题目进行强制换行，题目无法对齐，尝试加空格但是无法编译

**Comment by weiquanmao** [comment]
确实没有考虑太长的标题，建议你根据自己标题长度自行调整一下：
+ `buaa.cls`第643行修改行间距
+ `buaa.cls`第652行修改标题和作者信息的间距

**Comment by LaiPiXiong** [comment]
好的，谢谢

**Comment by LaiPiXiong** [comment]
我又定义了一个Title，题目长的时候，再第二行输入题目太长的部分就可以了
