### ISSUE TITLE
发现并解决的几个问题

### ISSUE THREAD

**Issue by SIRwkp** [CheckBoxStudio/BUAAThesis#27]
感谢前辈做的这个论文模板。

发现几个小问题，这里提一下，希望有助于其他人。

1、按照《手册》样张，.cls 文件所有的“指导老师”应该是“指导教师”。

2、英文标题页，Docrtor of Philosophy 拼写错误。

3、《手册》样张提名页，“学习时间自” “起止” 的对齐位置不符，在“起止”前加两个空格可以实现对齐。
同一页 “博士学位论文” 字间距太大了，将值改成11，6个汉字5个空格，与样张相似度更高。

4、如果只用 xelatex 编译则会出现无法加粗英文字体，经验证只需要再多运行一次 pdflatex 就可以解决。

**Comment by weiquanmao** [comment]
nice work! 🍻

**Comment by WayneLee1023** [comment]
> 感谢前辈做的这个论文模板。
> 
> 发现几个小问题，这里提一下，希望有助于其他人。
> 
> 1、按照《手册》样张，.cls 文件所有的“指导老师”应该是“指导教师”。
> 
> 2、英文标题页，Docrtor of Philosophy 拼写错误。
> 
> 3、《手册》样张提名页，“学习时间自” “起止” 的对齐位置不符，在“起止”前加两个空格可以实现对齐。
> 同一页 “博士学位论文” 字间距太大了，将值改成11，6个汉字5个空格，与样张相似度更高。
> 
> 4、如果只用 xelatex 编译则会出现无法加粗英文字体，经验证只需要再多运行一次 pdflatex 就可以解决。

强强强！马上提交论文了，这个帖子也太有用了吧

**Comment by WayneLee1023** [comment]
我的问题是，仅使用XeLatex会导致英文字体不加粗，再使用PdfLatex会导致中英文之间的间距变窄。

**Comment by WayneLee1023** [comment]
更正问题：使用XeLatex会导致英文字体默认显示为宋体，所以论文中的英文会看起来比Times New Roman更加细，而且无法对英文加粗。在字体设置部分使用  \setmainfont{Times New Roman} 可解决该问题
