### ISSUE TITLE
BibTex无法编译出正确的参考文献，引用全是问号

### ISSUE THREAD

**Issue by bitzhangcy** [CheckBoxStudio/BUAAThesis#29]
编译环境为TexStudio+TexLive2020，XeLatex和BibTex或Biber进行编译，发现都无法\cite等引用命令都是？，无法正确编译，且参考文献那一章也没有显示。
![image](https://user-images.githubusercontent.com/44028660/102167717-e702c880-3ec9-11eb-9531-806f133b2f45.png)

我编译的时候对原文件没有修改，是直接编译的

**Comment by weiquanmao** [comment]
多编译几次试试，可能是编译链顺序不对或不完整导致

**Comment by hddbuaa** [comment]
> 多编译几次试试，可能是编译链顺序不对或不完整导致

大神，我也遇到了一样的问题，各种编译方法都试过n多次了，依旧没有参考文献，我的环境是TeXstudio 2.12.22 + MiTeX 4.2，有其他解决方法吗

**Comment by deepmeng** [comment]
可以试试这个：

\Bib{bst/GBT7714-2015}{ref}
\bibliography{ref}

编译出来后再把下面一行删掉
