### ISSUE TITLE
我想把这个修改成基于 TeX Live的版本，工作量大吗

### ISSUE THREAD

**Issue by fucusy** [CheckBoxStudio/BUAAThesis#3]
当前版本是基于CTex，想咨询一下，我想把这个修改成基于 TeX Live的版本，工作量大吗。
因为为个版本在PDF浏览的时候，无法将其中的完整文字复制出来，复制，粘贴之后很容易错乱。

比如说，想复制浅蓝色背景这一块文字，
<img width="626" alt="screen shot 2018-01-24 at 9 54 52 am" src="https://user-images.githubusercontent.com/5172310/35310499-b404749c-00ec-11e8-8ba4-4b2a73b9c64a.png">

粘贴的结果是，
Liang Wang    [24]               的步态   的                    的         的     0    360               360          360 的  向                                 监   的       的                        的

**Comment by fucusy** [comment]
可以帮我一起把这个改成基于TeX Live，或者其它的什么可以解决这个bug的版本吗

**Comment by weiquanmao** [comment]
我现在其实也还在学习LaTeX中，很多都还不懂。至于移除CTex，需要涉及的可能有a)中文解决方案和b)样式两方面吧，具体工作量我也没概念。如果你有什么可行解决方案或想法的话，我很乐意参与其中。

-- Good Luck

**Comment by fucusy** [comment]
我还是决定放弃移除CTex，改用Word了，\叹气，学校查重需要DOC的格式。
谢谢你的回复。

**Comment by sparrow-jsl** [comment]
你是指北航图书馆的查重不能用pdf，只能用doc吗？ @fucusy

**Comment by fucusy** [comment]
@sparrow-jsl 班长是建议用WORD,没有说一定不能用PDF，但是这个PDF解析出来很可能是乱码，我就决定用WORD了

**Comment by sparrow-jsl** [comment]
*{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我今天用pdflatex试编译了一下下载的模板，报错！undefined control sequence.  \ctexset   {%网上查了半天没找到解决方法，你知道这是什么原因吗？



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.5;
        }
    
Best wishes,ShaolingSchool of Electronic and Information Engineering, Beihang UniversityTel: +86 18813166272---------------------------------------------------------------------------------------------祝身体健康，万事顺利！学生：景少玲北京航空航天大学 电子信息工程学院Tel: +86 18813166272

                


    在2018年1月25日 18:59，chenqiang<notifications@github.com> 写道： 


@sparrow-jsl 班长是建议用WORD,没有说一定不能用PDF，但是这个PDF解析出来很可能是乱码，我就决定用WORD了
