### ISSUE TITLE
2021年11月北航研究生院出了新的论文撰写规定……

### ISSUE THREAD

**Issue by kxgy2018** [CheckBoxStudio/BUAAThesis#33]
不知道楼主提供的LaTex模板能够对应update一下，新的论文撰写规定可见：https://github.com/ixzhao/BUAA_Dissertation_Template。整体上变化不太大。

**Comment by weiquanmao** [comment]
把密级处理了一下（\sa [2eaf](2eaf1217c2c9bf4f6aad5efe11f70b6afbe0a10b)）,其他宽度之类的就没调整了，还有哪些地方须要调整的麻烦指出一下

**Comment by deepmeng** [comment]
> 

新规定变化大吗

**Comment by kxgy2018** [comment]
我也还没有仔细对比过，不过好像格式审查表的内容有一些变化。例如参考文献每一条最后没有那个点。。。
[宇航学院-研究生学位论文格式审查表-新.pdf](https://github.com/CheckBoxStudio/BUAAThesis/files/8174126/-.-.pdf)

**Comment by kxgy2018** [comment]
> 把密级处理了一下（\sa [2eaf](2eaf1217c2c9bf4f6aad5efe11f70b6afbe0a10b)）,其他宽度之类的就没调整了，还有哪些地方须要调整的麻烦指出一下

新版本规定参考文献的格式里面，要把**每行最后的点删掉**（如下），请问这个应该怎么修改模板呢？
[3] 李贝贝，韩冰，田甜，等. 吉林一号视频卫星应用现状与未来发展[J]. 卫星应用, 2018, (03): 23-27
[4] 陆茜. 北斗三号全球卫星导航系统建成开通[J]. 国际太空, 2020, (08): 10-12

**Comment by kxgy2018** [comment]
确实可以实现，太感谢了！对应修改之后，重新build之前，把编译产生的文件删除，这样新生成PDF的参考文献就没有最后的点了。再次感谢大佬~~

**Comment by kxgy2018** [comment]
> 注释`GBT7714-2005`的`L483`
> 
> ```
> cap.period write$
> ```
> 
> 改为
> 
> ```
> %cap.period write$
> ```
> 
> 注释`GBT7714-2015`的`L181`
> 
> ```
> { add.period$
> ```
> 
> 改为
> 
> ```
> { %add.period$
> ```
> 
> 现在标准改成这样了?!如果确实调整了，后续更新入库。请先自行调整。

**Comment by kxgy2018** [comment]
> 把密级处理了一下（\sa [2eaf](2eaf1217c2c9bf4f6aad5efe11f70b6afbe0a10b)）,其他宽度之类的就没调整了，还有哪些地方须要调整的麻烦指出一下

附录A中的第1个公式为“(A1)”。你好，新规定里面附录的公式引用是(A1)(A2)这样，请问怎样把现在(A.1)的格式调整一下？
