### ISSUE TITLE
自动换行不太友好啊

### ISSUE THREAD

**Issue by deepmeng** [CheckBoxStudio/BUAAThesis#36]
我发现行末有公式或者英文单词的时候，换行就不太好使了。
除了手动调，还有啥好办法吗

![image](https://user-images.githubusercontent.com/8176780/156921249-3bf1ebb8-ff72-4510-ac3f-f99d2abf9de1.png)

**Comment by weiquanmao** [comment]
应该是'Multivariate'太长，又不能断。试试'Multi-variate'呢。
