### ISSUE TITLE
索引序号的问题

### ISSUE THREAD

**Issue by deepmeng** [CheckBoxStudio/BUAAThesis#37]
遇到一个问题，请教一下。我希望参考文献的序号是从第一章绪论开始排。

现实情况：如果我在任意图片的标题中插入了一个参考文献的引用。在生成PDF的时候，我猜由于先要生成图片列表页，导致参考文献的序号不是从第一章绪论中的引用开始排号。

请问这个问题有人遇到过吗？有没有方法解决？

**Comment by weiquanmao** [comment]
多编译几次就可以了，我尝试是可以的。原因不太清楚，估计是内部机制的原因，计算更新啥的。

**Comment by deepmeng** [comment]
解决了，遇到同样问题的同学可以试试添加以下代码。

\usepackage{notoccite}
