### ISSUE TITLE
段落格式问题

### ISSUE THREAD

**Issue by LegolasUndomiel** [CheckBoxStudio/BUAAThesis#39]
您好，我在编译完之后发现有的段落之间空隙非常大，就像图片中这样，请问这是什么原因呢，该调整哪里呢
![2022-04-21_10-34](https://user-images.githubusercontent.com/73049640/164360249-5f8b8ae4-4319-48da-8472-8bd8cce980b9.png)
？

**Comment by weiquanmao** [comment]
方便看下你上下页的情况吗

**Comment by LegolasUndomiel** [comment]
![page1](https://user-images.githubusercontent.com/73049640/164952656-0b4af0d3-77b4-4fa2-bc54-d1166ec72045.png)
![page2](htt
![page3](https://user-images.githubusercontent.com/73049640/164952670-a07f9820-de4f-4e27-b73c-77edbbf0581a.png)
ps://user-images.githubusercontent.com/73049640/164952662-76830510-5054-43b2-aa37-ecea320c1d15.png)

**Comment by LegolasUndomiel** [comment]
![page1](https://user-images.githubusercontent.com/73049640/164952695-3134c18f-1b28-4766-a363-fbd42422452c.png)
![page2](https://user-images.githubusercontent.com/73049640/164952699-65a7d810-afc3-4c85-97ed-5afca4a1bd80.png)
![page3](https://user-images.githubusercontent.com/73049640/164952703-9a653c7f-a43c-414f-bcfe-ee5865cd4bd2.png)

**Comment by LegolasUndomiel** [comment]
然后我在buaa.cls文件中加了\setlength{\parskip}{0pt}之后变成这样了
![page1](https://user-images.githubusercontent.com/73049640/164952935-c60787a9-9525-46f4-ac6e-ae0a796384c9.png)
![page2](https://user-images.githubusercontent.com/73049640/164952937-5922395c-e551-443d-be45-8de9ff1455cc.png)
![page3](https://user-images.githubusercontent.com/73049640/164952940-40bb4ee4-bb53-42de-88d8-eb795ed9f595.png)

**Comment by LegolasUndomiel** [comment]
请问这是不是cls文件中没有定义各种格式的间距造成的？

**Comment by weiquanmao** [comment]
查到一个博客，里面说`要注意的是 LaTeX 宁愿在一页中留下空白，也不愿把一个标题放在此页的底部`，挺认可。
但为什么`\parskip`可以控制就不太清楚了，还需要学习啊~。

[LaTeX中的各种距离设置总结](https://www.bbsmax.com/A/QW5YVXyKdm/)

**Comment by kxgy2018** [comment]
> parskip

请问这里的一行是加在哪里呢？现在有没有更好的解决方案呀？

**Comment by weiquanmao** [comment]
我加在cls了，其他方案不清楚

**Comment by LegolasUndomiel** [comment]
好的谢谢学长

**Comment by LegolasUndomiel** [comment]
问题最终解决方案： 在buaa.cls文件中添加语句\setlength{\parskip}{0pt}后重新编译
使用这一方案修改后，会出现前一段结尾有空白，而下一段的标题在新的一页，原因如[weiquanmao](https://github.com/weiquanmao)学长所言，可以适当缩写前一段消除奇怪的空白/分页问题

> 查到一个博客，里面说`要注意的是 LaTeX 宁愿在一页中留下空白，也不愿把一个标题放在此页的底部`，挺认可。 但为什么`\parskip`可以控制就不太清楚了，还需要学习啊~。
> 
> [LaTeX中的各种距离设置总结](https://www.bbsmax.com/A/QW5YVXyKdm/)
