### ISSUE TITLE
 下载模板之间运行遇到问题  undefined control sequence  \ctexset {%

### ISSUE THREAD

**Issue by sparrow-jsl** [CheckBoxStudio/BUAAThesis#4]
下载buaa的latex模板后，尝试用pdflatex编译,但是报错如下：
！ undefined control sequence
1.257 \ctexset 
                 {%
?

请问这是什么问题，在网上查了半天没找到解决办法，有人提议更新mixtex，但是更新后编译直接报错，该怎么解决呢？谢谢！

**Comment by weiquanmao** [comment]
你的MikTeX和CTeX版本是多少？会不会是CTeX版本过低？

**Comment by sparrow-jsl** [comment]
不知道，我装的Ctex2.9.2.164_full .

**Comment by weiquanmao** [comment]
问题解决了吗？

**Comment by sparrow-jsl** [comment]
*{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
没有，放弃了。



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.5;
        }
    
Best wishes,ShaolingSchool of Electronic and Information Engineering, Beihang UniversityTel: +86 18813166272---------------------------------------------------------------------------------------------祝身体健康，万事顺利！学生：景少玲北京航空航天大学 电子信息工程学院Tel: +86 18813166272

                


    在2018年2月26日 18:37，WeiQM<notifications@github.com> 写道： 


问题解决了吗？
