### ISSUE TITLE
单面打印格式问题

### ISSUE THREAD

**Issue by LegolasUndomiel** [CheckBoxStudio/BUAAThesis#40]
单面打印输出的pdf文件中，论文中文封面、英文封面、提名页、独创性声明页这四页是连着的，中间没有空白页

**Comment by weiquanmao** [comment]
不太理解你的需求，单页打印的空白页是什么用途？

**Comment by LegolasUndomiel** [comment]
最近排版把自己都搞傻了。。。

**Comment by LegolasUndomiel** [comment]
还有一个问题，就是有些字体该加粗的但是没有加粗，包括英文封面的论文题目、作者、指导老师，摘要页的Abastract和key words
![problem1](https://user-images.githubusercontent.com/73049640/166136811-b79d34f3-9364-4533-a183-afc428c67142.png)
![issue2](https://user-images.githubusercontent.com/73049640/166136817-2be23a50-8cdf-4059-9fd6-f34114e2693f.png)
![issue3](https://user-images.githubusercontent.com/73049640/166136821-2619d9d1-5d86-48bd-ba34-a2d4f7c78398.png)
