### ISSUE TITLE
会议论文引用格式

### ISSUE THREAD

**Issue by kxgy2018** [CheckBoxStudio/BUAAThesis#43]
当bib文件中没有会议举办的地点的时候，参考文献中就会出现[S.1.]作为代替，不知道这个[S.l.]能否去掉呢？
[1] Srivastava N, Mansimov E, Salakhudinov R. Unsupervised learning of video representations using lstms[C]. International Conference on Machine Learning. [S.l.]: PMLR, 2015: 843–852

**Comment by kxgy2018** [comment]
> 当bib文件中没有会议举办的地点的时候，参考文献中就会出现[S.1.]作为代替，不知道这个[S.l.]能否去掉呢？ [1] Srivastava N, Mansimov E, Salakhudinov R. Unsupervised learning of video representations using lstms[C]. International Conference on Machine Learning. [S.l.]: PMLR, 2015: 843–852

已解决~

**Comment by LegolasUndomiel** [comment]
请问是如何解决的？我也遇到同样的问题

**Comment by kxgy2018** [comment]
> 

[S.l.]:解决可参见[链接](https://github.com/BHOSC/BUAAthesis/issues/155)；需要对应调整第872和908行的代码，以去除这部分；

**Comment by kxgy2018** [comment]
> 请问是如何解决的？我也遇到同样的问题

[S.l.]:解决可参见[链接](https://github.com/BHOSC/BUAAthesis/issues/155)；需要对应调整第872和908行的代码，以去除这部分；
