### ISSUE TITLE
iftex的关键词大小写问题

### ISSUE THREAD

**Issue by leiguan118** [CheckBoxStudio/BUAAThesis#45]
我的环境是texlive2019包，编译时出现问题，错误提示是在buaa.cls文件里面的iftex包那里。
`\usepackage{iftex}
\ifpdftex
\else
\setmainfont{Times New Roman}
\fi`
我这里能编译通过的写法应该是\ifPDFTeX，需要注意大小写

**Comment by weiquanmao** [comment]
👌
