### ISSUE TITLE
电子文献的引用顺序有问题

### ISSUE THREAD

**Issue by AlphaCat00** [CheckBoxStudio/BUAAThesis#48]
2021撰写规定中的格式及样例

>［序号］作者．电子文献题名[文献类型/载体类型] ．文献网址或出处, 发表或更新日期/引用日期(任选)

> ［21］王明亮．中国学术期刊标准化数据库系统工程的[EB/OL] , http://www.cajcd.cn/pub/wml.txt/980810-2.html, 1998-08-16/1998-10-04

此模板生成的

> [1] 王明亮. 中国学术期刊标准化数据库系统工程的[EB/OL]. 1998. http://www.cajcd.cn/pub/wml.txt/980810-2.html

测试用的ref.bib

    @misc{db,
      author={王明亮},
      title = {中国学术期刊标准化数据库系统工程的},
      url={http://www.cajcd.cn/pub/wml.txt/980810-2.html},
      year = {1998},
    }

**Comment by weiquanmao** [comment]
调整了bst格式[451f67a](https://github.com/CheckBoxStudio/BUAAThesis/commit/451f67a11c99a05bb128a006c32a900c61e114a0)

学校手册上的参考格式好像和GBT7714-2015标准有出入
