### ISSUE TITLE
「申请学位级别」的错位问题

### ISSUE THREAD

**Issue by xxgj** [CheckBoxStudio/BUAAThesis#50]
您好，

首先非常感谢您花时间编写并开源本模板，为我节约了很多时间:)

不过我在撰写论文的过程中，似乎遇到了一个问题，希望您可以拨冗解答，不胜感激！具体是这样的，我发现[目前版本的PDF](https://github.com/CheckBoxStudio/BUAAThesis/blob/master/Template.pdf)中，第五页的「申请学位级别」一栏，「工学」与「硕士」两词似乎存在粘连，详见下图：

![image](https://user-images.githubusercontent.com/20851683/203243932-cd8d17e9-4ee0-4d49-8c1c-20c6661ef1c3.png)

我简单检查了一下[代码](https://github.com/CheckBoxStudio/BUAAThesis/blob/master/buaa.cls#L784)，发现存在`\hspace{-0.5\ccwd}`这一条指令。不太清楚我有没有遗漏其他要点，如果确实需要存在该指令，想和您了解更具体的原因。如果不需要存在，我可以帮忙提一个PR修复这个问题。

提前感谢您的回复！再次感谢您对开源社区作出的卓越贡献。

祝好，致敬
xxgj

**Comment by weiquanmao** [comment]
已修复，感谢反馈 👍
