### ISSUE TITLE
空白页问题

### ISSUE THREAD

**Issue by rnlee1998** [CheckBoxStudio/BUAAThesis#51]
您好，我十分喜欢您的工作，但是我有一些问题想询问您。
[当我新建一个chapter时候，会多产生一个新的空白页，请问这是您的模板这样设置的吗，如果我不想要这个空白页，或者是我该部分就只有一页的内容，我应该如何去除这个空白页呢？

**Comment by weiquanmao** [comment]
双面打印模式下，新章节从奇数页开始，可能会在前面（上一页内容为奇数页）插入空白页。
请确认下你是不是这个情况

**Comment by rnlee1998** [comment]
> 双面打印模式下，新章节从奇数页开始，可能会在前面（上一页内容为奇数页）插入空白页。 请确认下你是不是这个情况

感谢您的回答，问题解决了
