### ISSUE TITLE
目录颜色修改

### ISSUE THREAD

**Issue by jingzhengli** [CheckBoxStudio/BUAAThesis#52]
请问目录颜色是蓝色的，这个如何修改成黑色的呢，谢谢～

**Comment by weiquanmao** [comment]
你试试buaa.cls 400行左右


\hypersetup{%

  colorlinks=true,

  bookmarksnumbered=true,


将colorlinks改成false

From Quanmao Wei.

在 2023年1月29日，22:58，jingzhengli ***@***.***> 写道：

﻿

请问目录颜色是蓝色的，这个如何修改成黑色的呢，谢谢～

**Comment by jingzhengli** [comment]
感谢感谢。
可以了。
另外我试了下 Template.tex 84行 \refcolor{on}  on 改成off也可以。
