### ISSUE TITLE
前后两页左右没有对齐..

### ISSUE THREAD

**Issue by jingzhengli** [CheckBoxStudio/BUAAThesis#53]
仔细一看，上一页和下一页 左右边距都没有对齐。这个问题怎么解决呢？

<img width="217" alt="image" src="https://user-images.githubusercontent.com/40593161/216899450-93702a7e-6f60-470b-8a3b-c2448910a4e2.png">

**Comment by jingzhengli** [comment]
> 仔细一看，上一页和下一页 左右边距都没有对齐。这个问题怎么解决呢？
> 
> <img alt="image" width="217" src="https://user-images.githubusercontent.com/40593161/216899450-93702a7e-6f60-470b-8a3b-c2448910a4e2.png">

好像模版是这么要求的，抱歉哈

**Comment by weiquanmao** [comment]
应该是双页打印，左右页留的页边距不同
