### ISSUE TITLE
可以设置中英文图表目录嘛？

### ISSUE THREAD

**Issue by Chy-ang** [CheckBoxStudio/BUAAThesis#56]
需要生成中英文的图表目录，有什么办法

**Comment by socod** [comment]
> 需要生成中英文的图表目录，有什么办法

可以看一下[Pull Request](https://github.com/CheckBoxStudio/BUAAThesis/pull/57/commits/6b428dd055f24777da82e94bcfb51b612dcd65d5), 仅供参考.
