### ISSUE TITLE
中文句号后面的空格

### ISSUE THREAD

**Issue by yingxingcheng** [CheckBoxStudio/BUAAThesis#6]
全茂同学你好，北航论文这个模板输出的PDF版里面的中文句号是不是有点和word的不太一样，一般word后面都是有一点空格，这个能解决吗？另外，这个作为最后的PDF可以直接提交吗？word写的实在是太难受了！！！

**Comment by weiquanmao** [comment]
已取消原有的半角标定设定，改为全角。同时将行伸缩设为2个汉字长度以改善中午标点断行问题。
[Check me](86dbf2a84762e9f07c43a16d9821bb147b628751)
```
\ctexset{%
  punct=quanjiao, % 全角
  autoindent=2,  % 缩进
  linestretch=2, % 行伸缩
}
```
