### ISSUE TITLE
长表格处报错

### ISSUE THREAD

**Issue by fangzth** [CheckBoxStudio/BUAAThesis#61]
最新模板下载下来，在编译时在长表格处报错。
line 233 Misplaced \noalign. \bicaption[长表格演示]{长表格演示}{long table}。

**Comment by weiquanmao** [comment]
1. 确认你的长表格标题为\bicaption[]{}[]{}的格式（不需要的参数可以空着），\bicaption[]{}{}为非正确语法，我在最新的模板中已经更新。
2. 确认bicaption宏包为较新版本，旧版本的\bicaption对longtable的支持有问题
3. 如果你不需要使用双语标题，请改用\caption[]{}  (单标题的\bication[]{}应该也可以吧)
